http:
  port: 80
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  api:
    host: localhost
    paths: ['/api','/api/*']
  bot:
    host: localhost
    paths: ['/bot','/bot/*']
  puppet:
    host: localhost
    paths: ['/puppet','/puppet/*']
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  apiService:
    url: 'http://localhost:3003'
  botService:
    url: 'http://localhost:3002'
  puppetService:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  apiPipeline:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: apiService
              changeOrigin: true
  botPipeline:
    apiEndpoints:
      - bot
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: botService
              changeOrigin: true
  puppetPipeline:
    apiEndpoints:
      - puppet
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: puppetService
              changeOrigin: true