http:
  port: ${PORT}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: '*'
    paths:
      - '/bot'
      - '/bot/*'
      - '/pricEmpire/*'
      - '/rollbit'
      - '/wishlistItems'
      - '/wishlistItems/*'
serviceEndpoints:
  apiService:
    url: ${WEB_API}
  botService:
    url: ${BOT_API}
  puppetService:
    url: ${PUPPET_API}
policies:
  - proxy
  - moesif
  - auth0
  - request-transformer
pipelines:
  apiPipeline:
    apiEndpoints:
      - api
    policies:
      - moesif:
      - auth0:
          - action:
              domain: 'https://suphero.eu.auth0.com'
      - request-transformer:
          - action:
              body:
                add:
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: apiService
              changeOrigin: true