http:
  port: ${PORT}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  api:
    host: '*'
    paths: ['/bot', '/bot/*', '/pricEmpire/*', '/rollbit', '/wishlistItems', '/wishlistItems/*']
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  apiService:
    url: ${WEB_API}
  botService:
    url: ${BOT_API}
  puppetService:
    url: ${PUPPET_API}
policies:
  - jwt
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  apiPipeline:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - jwt:
        - action:
            secretOrPublicKeyFile: ./key/pubKey.pem
            checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: apiService
              changeOrigin: true